# Generated by Django 5.2.13 on 2026-04-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
